### ISSUE TITLE
How can we change the name of the downloaded file?

### ISSUE THREAD

**Issue by mehmetgokkaya** [FlorianLeChat/YouTube-Downloader#1]
i try %(title)s-%(id)s.%(ext)s but not working

**Comment by FlorianLeChat** [comment]
Thanks for the feedback, the previous code could not support the change of the output title, with https://github.com/FlorianLeChat/YouTube-Downloader/commit/ba1328f6c40de69602cbc44cc4092c2999f8f364 and the latest commits, this should be fixed. The default title now uses the one you mentioned above which is also the same with YouTubeDL. Let me know if there is still an issue!
