### ISSUE TITLE
How to use it? i get this error.

### ISSUE THREAD

**Issue by ExIfDev** [FlorianLeChat/YouTube-Downloader#20]
[Fri Jan 05 14:48:21.499678 2024] [php7:warn] [pid 14134] [client 192.168.1.143:59186] PHP Warning:  require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/index.php on line 4
[Fri Jan 05 14:48:21.508504 2024] [php7:error] [pid 14134] [client 192.168.1.143:59186] PHP Fatal error:  require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/index.php on line 4

**Comment by FlorianLeChat** [comment]
Did you install all necessary Composer dependencies? (`composer install`)

**Comment by FlorianLeChat** [comment]
No news, I guess your issue is solved! 👍
