### ISSUE TITLE
Allow using your instance from Russia

### ISSUE THREAD

**Issue by legovo** [FlorianLeChat/YouTube-Downloader#3]
please

**Comment by FlorianLeChat** [comment]
If you are talking about the code itself, I do not apply any restriction to use from any country. If you are talking about my showcase website, it uses cloudflare to secure my traffic and as far as I know, I have not applied any particular restriction for users from Russia. If you can give me more information, I would be happy to help you.

In any case, you can freely host the project on your own computer or deploy an instance through the Docker image (if you have some knowledge in this domain), you will not depend on my infrastructure.

**Comment by legovo** [comment]
I can connect freely from Psiphon VPN, but when I connect directly I get a Cloudflare message saying that "The site owner may have set restrictions that prevent you from accessing the site". That's it.

**Comment by FlorianLeChat** [comment]
Oops you're right, I had excluded a long time ago access from non-European countries, it's fixed, apologies.
